Feat/add customers
michaelrodriguess/customer-service pull request #7
Opened 2024-12-24 20:53 UTC by michaelrodriguess

This feature is to create endpoint to add a new customers.

**Tests below**
Requests:
![image](https://github.com/user-attachments/assets/e7fc125e-581f-4101-b93f-25364d6ce462)

Persistencia de dados:
![image](https://github.com/user-attachments/assets/f5f8938b-78e6-4cfa-94c4-5498a52c65c7)

Logs:
![image](https://github.com/user-attachments/assets/4c5dc84c-d9ad-4989-8514-1aacb9412193)

2024-12-24 21:27 UTC, didibrabosa approved these changes
congrats bro!

2024-12-25 19:02 UTC, AurelioNM requested changes
Feliz natal

2024-12-25 19:02 UTC, AurelioNM commented on routes/customer_router.py
> +    logger.info(f"[ROUTER]: Creating customer with email={customer_data.email}")
Dá uma olhada no arquivo de config de logs, do product-service 
Vc vai ver q pela config, o log ja carimba o arquivo que ele está. Aí não precisa botar a [CAMADA] direto na mensagem.
Por isso o __name__ qnd o logger é instanciado 

Como é uma rota que recebe um body, vc pode logar ele inteiro, não precisa ser só o email

2024-12-25 19:02 UTC, AurelioNM commented on routes/customer_router.py
> +    logger.info(f"create customer request finished with response={customer_data.model_dump()}")
Muito cuidado com os logs, eles são o que vão te ajudar na hora de fazer troubleshooting e resolver incidentes
O response que voce está logando não é de fato o que vc está retornando

2024-12-25 19:02 UTC, AurelioNM commented on services/customer_service.py
> +        try:
Se tivesse alguma validação de negocios aqui, eu acharia valido o try/catch 
Mas como o service só está sendo um proxy para o storage, não vejo necessidade do try/catch nessa camada

2024-12-25 19:02 UTC, AurelioNM commented on storages/customer_storage.py
> +        self.logger.info(f"[STORAGE]: Creating customer with email={customer.email}")
Aqui, mesmo tendo a camada storage no log, é bom vc indicar nos logs dessa camada que vc está lidando com o banco de dados 
Então eu trocaria para 
`self.logger.info(f"Inserting product in DB")`

2024-12-25 19:02 UTC, AurelioNM commented on storages/customer_storage.py
> +            self.logger.error(f"Error in storage layer: {ex}")
Log ta muito genérico aqui, é importante vc deixar explicito qual operação falhou no log de error

2024-12-25 19:02 UTC, AurelioNM commented on storages/customer_storage.py
> +                    VALUES (%s, %s, %s, NOW(), NOW());
No caso de um INSERT, o updated_at não vai ser inserido. O valor default da coluna vai ser null msm.
Só inserimos ele em casos de atualização

2024-12-25 19:02 UTC, AurelioNM commented on storages/customer_storage.py
> +                self.db.commit()
Acho q esse commit() aqui vai te causar problemas. Faz o seguinte teste

- Cria um customer
- Tenta cria um segundo customer com o mesmo email 
  - O constraint "UNIQUE" da coluna, não vai deixar vc criar
- Cria um terceiro customer com email novo
  - Voce provavelmente vai tomar um erro falando que a transacao não foi fechada, no ultimo insert (segunda requisicão)

Por isso acho q esse commit deveria ficar num finally, até acharmos uma solução melhor

2024-12-25 19:31 UTC, AurelioNM commented on storages/customer_storage.py
> +                self.db.commit()
Pensando agora, talvez funcione manter o commit aqui, e colocar o rollback no catch
Se puder testar isso... talvez nem precise do finally com commit

2024-12-26 02:56 UTC, Arthuralentejo commented on storages/customer_storage.py
> +            self.logger.error(f"Error in storage layer: {ex}")
Esse problema nasce de vc estar capturando uma exception generica. Vc não quer pegar todos os erros que rolam ai, apenas os de database (pq são os erros esperados).

2024-12-26 21:05 UTC, michaelrodriguess commented on routes/customer_router.py
> +    logger.info(f"[ROUTER]: Creating customer with email={customer_data.email}")
feito.

2024-12-26 21:06 UTC, michaelrodriguess commented on services/customer_service.py
> +        try:
removido o try catch!

2024-12-26 21:22 UTC, michaelrodriguess commented on storages/customer_storage.py
> +        self.logger.info(f"[STORAGE]: Creating customer with email={customer.email}")
feito.

2024-12-26 21:33 UTC, michaelrodriguess commented on storages/customer_storage.py
> +            self.logger.error(f"Error in storage layer: {ex}")
aprumado.

2024-12-26 22:28 UTC, michaelrodriguess commented on storages/customer_storage.py
> +                    VALUES (%s, %s, %s, NOW(), NOW());
concordo removido também mano.

2024-12-26 22:32 UTC, michaelrodriguess commented on storages/customer_storage.py
> +                self.db.commit()
perfeito. Adicionei o rollback para garantir a integridade do banco! Coloquei um rollback pra lidar com violação de unique constrait e para erros inesperados :)

2024-12-26 23:13 UTC, AurelioNM approved these changes

2024-12-27 22:23 UTC, Arthuralentejo requested changes, later dismissed

2024-12-27 22:23 UTC, Arthuralentejo commented on storages/customer_storage.py
> +        except Exception as ex:
Mesma coisa desse pr aqui
https://github.com/michaelrodriguess/customer-service/pull/9#discussion_r1898732160

2024-12-29 02:45 UTC, michaelrodriguess commented
Handle the change requests made and below we have the tests performed after resolving the conflict to merge.

Requests:
![image](https://github.com/user-attachments/assets/f131a0ee-f128-4d00-a39d-d7719ba82258)

Persistence:
![image](https://github.com/user-attachments/assets/4c483879-7c1e-4d04-852a-77c9ecf5717c)

2024-12-29 18:27 UTC, didibrabosa reviewed
looks good to me!

2024-12-29 19:49 UTC, AurelioNM approved these changes

2024-12-29 21:36 UTC, merged