creating delete route
michaelrodriguess/customer-service pull request #8
Opened 2024-12-25 21:45 UTC by didibrabosa

**Tests down bellow:**

_Resquest:_

![Captura de tela de 2024-12-25 18-36-11](https://github.com/user-attachments/assets/16c53502-90dd-46da-be28-fbb3a10b4814)

_Data update:_

![Captura de tela de 2024-12-25 18-37-44](https://github.com/user-attachments/assets/aa004c0e-870d-4032-acf3-7ff1aabd8dfe)

_Logs:_

![Captura de tela de 2024-12-25 18-38-12](https://github.com/user-attachments/assets/94f86b6d-eb50-4320-a5f3-9d2e3b01b77e)

2024-12-25 22:50 UTC, AurelioNM commented on storages/customer_storage.py
> +                    return None
Aqui ao invés de retornar null, o certo seria dar raise em alguma exception que encaixe nesse cenário
Aí a camada de route da um catch nessa exception, e retorna 404

2024-12-25 22:51 UTC, AurelioNM commented on services/customer_service.py
> +            if deleted_customer_id is None:
pode remover essa verificacao se o retorno é null. Levando em consideracao meu comentario no storage

2024-12-25 22:51 UTC, AurelioNM commented on services/customer_service.py
> +            return {"message": f"Customer id={customer_id} successfully deactivated."}
Não é responsabilidade do service montar o retorno da API, quem cuida disso é a camada de rotas

2024-12-25 22:53 UTC, AurelioNM commented on routes/customer_router.py
> +    return result
As demais rotas não retornam um `message: customer created` ou `message: customer updated`
Então na delete, o retorno apropriado seria um 204, sem body

2024-12-25 22:54 UTC, AurelioNM requested changes
Feliz natal

2024-12-26 22:27 UTC, AurelioNM commented on routes/customer_router.py
> +        logger.info("Delete customer request finished with response=204")
Ao invés de 204, sua api ta retornando 200

2024-12-26 22:29 UTC, AurelioNM commented on services/customer_service.py
> +        except Exception as ex:
Como não ta rolando nenhuma regra de negocio aqui, só está repassando a chamada pro storage, não acho q precise desse try/except aqui

2024-12-26 22:30 UTC, AurelioNM commented on storages/customer_storage.py
> +            self.logger.error(f"Error in storage layer: {ex}")
Importante deixar um `self.db.rollback()` aqui, pra quando der erro, ele conseguir fechar a transação no DB

2024-12-26 22:31 UTC, AurelioNM commented on storages/customer_storage.py
> +                return customer_id
Como o service não está usando esse retorno, pode remover ele

2024-12-27 22:22 UTC, Arthuralentejo requested changes

2024-12-27 22:22 UTC, Arthuralentejo commented on storages/customer_storage.py
> +        except Exception as ex:
Mesma coisa que coloquei nesse pr aqui
https://github.com/michaelrodriguess/customer-service/pull/9#discussion_r1898732160

2024-12-28 21:47 UTC, Arthuralentejo requested changes

2024-12-28 21:47 UTC, Arthuralentejo commented on routes/customer_router.py
> +    except DatabaseError as e:
Não tem pq capturar database error aqui no router, deixa ele estourar q o fast api trata de retornar 500. 

Vc so precisa capturar ele la no storage pra logar oq houve.

2024-12-28 21:48 UTC, Arthuralentejo commented on storages/customer_storage.py
> +            self.db.rollback(f"Failed to delete in DB: {ex}")
Pq vc ta printando uma mensgem dentro do rollback? Isso n deveria ser um log?

2024-12-28 22:00 UTC, didibrabosa commented on storages/customer_storage.py
> +            self.db.rollback(f"Failed to delete in DB: {ex}")
feito! tinha feito na pressa e nao me atentei nessa parte.

2024-12-28 22:09 UTC, AurelioNM approved these changes

2024-12-28 22:11 UTC, merged